OCC-11: Updating documentation for JS scripts
Lombiq/NodeJs-Extensions pull request #6
Opened 2022-07-25 16:22 UTC by DemeSzabolcs

OCC-11

2022-07-25 16:40 UTC, wAsnk approved these changes

2022-07-29 14:47 UTC, DAud-IcI requested changes

2022-07-29 14:47 UTC, DAud-IcI commented on Lombiq.NodeJs.Extensions/Docs/JavaScript.md
> +You will also need to add the following line to your project file in a `Property Group` to override the default script execution:
The future time and obligation are unnecessary complications here. 
Also only use backticks for code. Use underscores for key words. So either

```suggestion
Also add the following line to your project file in a _Property Group_ to override the default script execution:
```
or

```suggestion
Also add the following line to your project file in a `<PropertyGroup>` to override the default script execution:
```

2022-07-30 15:37 UTC, DemeSzabolcs commented
Strange, it says:
```
Error: Couldn't find any pull request whose title starts with "OCC-11:" in Lombiq/Open-Source-Orchard-Core-Extensions. Please create one.
```
But I don't think this was added to Open-Source-Orchard-Core-Extensions.

2022-07-30 15:39 UTC, DAud-IcI commented
It's in the `task/node-extensions` branch.

2022-07-31 16:08 UTC, merged