OSOE-430: Support a single NE instance per solution on Linux, too, in Lombiq.NodeJs.Extensions
Lombiq/NodeJs-Extensions pull request #74
Opened 2023-10-06 17:19 UTC by DAud-IcI

2023-10-14 13:37 UTC, DAud-IcI commented
Note the last commit (https://github.com/Lombiq/NodeJs-Extensions/pull/74/commits/6d8e16636f70a71eefa14a28312fe527182cbea3) that contains the fixes to various ESlint warnings, including some that aren't related to this issue. (because the auxiliary scripts in _Lombiq.NodeJs.Extensions/scripts/_ that are only used by node during the compilation don't get linted automatically)

2023-10-17 17:43 UTC, dministro requested changes

2023-10-17 17:43 UTC, dministro commented on Lombiq.NodeJs.Extensions/scripts/copy-assets.js
> +            const directoryToCopy = path.normalize(path.join(projectPath, assetSource));
`path.resolve()` seems a better choice to me instead of `path.join()` in case of absolute `assetSource`

2023-10-17 17:43 UTC, dministro commented on Lombiq.NodeJs.Extensions/scripts/copy-assets.js
> +                            : path.normalize(path.join(projectPath, assetsGroup.target));
`path.resolve()` same reason like above.

2023-10-17 17:43 UTC, dministro commented on Lombiq.NodeJs.Extensions/scripts/get-path.js
> +    if (typeof config[type] !== 'object' || !config[type][location]) return null;
Optional chaining:
```suggestion
    if (!config?.[type]?.[location]) return null;
```

2023-10-18 15:23 UTC, dministro approved these changes

2023-10-18 15:32 UTC, merged